### ISSUE TITLE
DEV MVP4 Update elastic version in u14all from 5.1.2 to 5.5.0

### ISSUE THREAD

**Issue by raksha78** [dry-dock/u14all#38] opened 2017-07-11 08:16 UTC

**Comment by raksha78** [comment] 2017-07-11 08:17
https://github.com/Shippable/pm/issues/8613

**Comment by kanthchandra** [comment] 2017-07-11 13:17
duplicate of https://github.com/dry-dock/u14all/issues/42

**Closed by kanthchandra** 2017-07-11 13:17 UTC
